# Основные настройки
Server=192.168.1.172
ServerActive=
HostnameItem=system.hostname

# Динамические метаданные через внешний скрипт
HostMetadataItem=system.run["C:\Program Files\Zabbix Agent 2\scripts\get_metadata.bat"]

# Логи
LogFile=C:\Program Files\Zabbix Agent 2\zabbix_agent2.log
LogFileSize=50
PidFile=C:\Program Files\Zabbix Agent 2\zabbix_agent2.pid

# Таймауты и безопасность
Timeout=30
AllowKey=system.run[*]

# Дополнительные пользовательские правила
Include=C:\Program Files\Zabbix Agent 2\zabbix_agent2.d\